[project]
name = "Zeraora"
dynamic = ["version"]
authors = [
    { name = "aixcyi", email = "75880483+aixcyi@users.noreply.github.com" },
]
description = "Zeraora lightweight collection of utilities that save your dev time."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    # https://pypi.org/classifiers/
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 4.1",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Framework :: Django :: 5.1",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Natural Language :: Chinese (Simplified)",
    "Topic :: Utilities",
    "Typing :: Typed",
]
requires-python = ">=3.10"
dependencies = [
    "typing_extensions>=4.14.0",
]


[project.urls]
Homepage = "https://docs.navifox.net/zeraora/"
Documentation = "https://docs.navifox.net/zeraora/"
Source = "https://github.com/aixcyi/zeraora"
Issues = "https://github.com/aixcyi/zeraora/issues"


[project.optional-dependencies]
client = [
    "requests>=2.27",
]
backend = [
    "django>=3.2",
]
restful = [
    "django>=3.2",
    "djangorestframework>=3.13",
]


[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
]


[dependency-groups]
latest = [
    "django",
    "djangorestframework",
    "requests",
    "typing-extensions",
]
stable = [
    "django==5.2.*",
    "djangorestframework==3.16.*",
    "requests==2.32.*",
    "typing-extensions==4.*",
]
legacy = [
    "django==3.2.*",
    "djangorestframework==3.13.*",
    "requests==2.27.*",
    "typing-extensions==4.14.0",
]
dev = [
    { include-group = "stable" },
]
test = [
    { include-group = "stable" },
]
test-latest = [
    { include-group = "latest" },
]
test-legacy = [
    { include-group = "legacy" },
]


[tool.setuptools.dynamic]
version = { attr = "zeraora.__version__" }


[tool.setuptools.packages.find]
include = ["zeraora*"]


[tool.uv]
conflicts = [
    [
        { group = "latest" },
        { group = "stable" },
        { group = "legacy" },
        { group = "dev" },
        { group = "test" },
        { group = "test-latest" },
        { group = "test-legacy" },
    ],
]
